In [1]:
import pandas as pd
import numpy as np

In [2]:
raw_cl = pd.read_csv('crime_landUse_MAN.csv')
raw_cl

,CrimeType,DayofWeek,TimeRange,Time,Day,Lot,LandUseID,LandUse,CrimeTypeID
0,ASSAULT,Sunday,20-21,20,1,33,4,Mixed Residential & Commercial Buildings,3
1,LARCENY,Monday,17-18,17,2,21,2,Multi-Family Walk-Up Buildings,1
2,LARCENY,Friday,23-24,23,6,29,8,Public Facilities & Institutions,1
3,LARCENY,Tuesday,18-19,18,3,36,5,Commercial & Office Buildings,1
4,HARASSMENT,Thursday,19-20,19,5,29,8,Public Facilities & Institutions,2
...,...,...,...,...,...,...,...,...,...
201570,LARCENY,Friday,17-18,17,6,62,4,Mixed Residential & Commercial Buildings,1
201571,LARCENY,Sunday,10-11,10,1,7,4,Mixed Residential & Commercial Buildings,1
201572,LARCENY,Friday,20-21,20,6,52,2,Multi-Family Walk-Up Buildings,1
201573,LARCENY,Sunday,20-21,20,1,1,9,Open Space and Outdoor Recreation,1
201574,LARCENY,Saturday,13-14,13,7,16,2,Multi-Family Walk-Up Buildings,1

In [3]:
from sklearn import preprocessing
#label = preprocessing.LabelEncoder()
#crime = label.fit_transform(raw_cl.CrimeType)
days = pd.get_dummies(raw_cl.DayofWeek)
landuses = pd.get_dummies(raw_cl.LandUse)
times = pd.get_dummies(raw_cl.TimeRange)
cl=pd.concat([landuses,times,days,raw_cl.CrimeTypeID],axis=1)
#cl['crime']=crime

In [4]:
cl

,Commercial & Office Buildings,Industrial & Manufacturing,Mixed Residential & Commercial Buildings,Multi-Family Elevator Buildings,Multi-Family Walk-Up Buildings,One & Two Family Buildings,Open Space and Outdoor Recreation,Parking Facilities,Public Facilities & Institutions,Transportation & Utility,...,22-23,23-24,Friday,Monday,Saturday,Sunday,Thursday,Tuesday,Wednesday,CrimeTypeID
0,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,3
1,0,0,0,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
2,0,0,0,0,0,0,0,0,1,0,...,0,1,1,0,0,0,0,0,0,1
3,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,1
4,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,1,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
201570,0,0,1,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
201571,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
201572,0,0,0,0,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
201573,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,1,0,0,0,1
201574,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1

In [5]:
from sklearn.model_selection import train_test_split
training,test=train_test_split(cl,train_size=0.8,random_state=42)

In [6]:
larceny = training.CrimeTypeID == 1
la = training[larceny]
la

,Commercial & Office Buildings,Industrial & Manufacturing,Mixed Residential & Commercial Buildings,Multi-Family Elevator Buildings,Multi-Family Walk-Up Buildings,One & Two Family Buildings,Open Space and Outdoor Recreation,Parking Facilities,Public Facilities & Institutions,Transportation & Utility,...,22-23,23-24,Friday,Monday,Saturday,Sunday,Thursday,Tuesday,Wednesday,CrimeTypeID
155239,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
125896,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,1
92378,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,1,0,0,1
66824,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
156043,0,0,0,0,0,0,0,0,0,1,...,0,1,0,0,0,0,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110268,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
103694,0,0,0,1,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
131932,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
146867,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,1
121958,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1

In [7]:
remove = training[training.CrimeTypeID == 1].sample(67000,random_state=42)
new_training = training[~training.index.isin(remove.index)]
#remove1 = new_training1[new_training1.crime == 1].sample(3064,random_state=42)
#new_training2 = new_training1[~new_training1.index.isin(remove1.index)]
#remove2=new_training2[new_training2.crime == 0].sample(736,random_state=42)
#new_training = new_training2[~new_training2.index.isin(remove2.index)]

In [8]:
larceny = new_training.CrimeTypeID== 1
la = new_training[larceny]
la

,Commercial & Office Buildings,Industrial & Manufacturing,Mixed Residential & Commercial Buildings,Multi-Family Elevator Buildings,Multi-Family Walk-Up Buildings,One & Two Family Buildings,Open Space and Outdoor Recreation,Parking Facilities,Public Facilities & Institutions,Transportation & Utility,...,22-23,23-24,Friday,Monday,Saturday,Sunday,Thursday,Tuesday,Wednesday,CrimeTypeID
92378,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,1,0,0,1
171485,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
194658,1,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
138845,0,0,0,0,0,0,1,0,0,0,...,0,0,0,1,0,0,0,0,0,1
91132,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194027,0,0,1,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
16023,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,1
110268,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
131932,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
146867,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,1

In [9]:
harassment = new_training.CrimeTypeID== 2
ha = new_training[harassment]
ha

,Commercial & Office Buildings,Industrial & Manufacturing,Mixed Residential & Commercial Buildings,Multi-Family Elevator Buildings,Multi-Family Walk-Up Buildings,One & Two Family Buildings,Open Space and Outdoor Recreation,Parking Facilities,Public Facilities & Institutions,Transportation & Utility,...,22-23,23-24,Friday,Monday,Saturday,Sunday,Thursday,Tuesday,Wednesday,CrimeTypeID
45847,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,1,0,0,2
40419,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,2
31148,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,2
156531,0,0,0,1,0,0,0,0,0,0,...,1,0,0,0,0,1,0,0,0,2
36053,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59735,0,0,0,1,0,0,0,0,0,0,...,1,0,0,0,0,0,1,0,0,2
175203,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,2
126324,1,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,2
112727,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,2
119879,0,0,1,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,2

In [10]:
assault = new_training.CrimeTypeID== 3
aa = new_training[assault]
aa

,Commercial & Office Buildings,Industrial & Manufacturing,Mixed Residential & Commercial Buildings,Multi-Family Elevator Buildings,Multi-Family Walk-Up Buildings,One & Two Family Buildings,Open Space and Outdoor Recreation,Parking Facilities,Public Facilities & Institutions,Transportation & Utility,...,22-23,23-24,Friday,Monday,Saturday,Sunday,Thursday,Tuesday,Wednesday,CrimeTypeID
35829,0,0,0,0,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,3
130760,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,3
93341,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,3
173119,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,3
152519,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84654,0,0,0,0,0,0,0,0,1,0,...,0,1,1,0,0,0,0,0,0,3
130523,1,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,3
84478,1,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,3
5311,0,1,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,3
87498,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,3

In [11]:
train,validation=train_test_split(new_training,train_size=0.8,random_state=42)

In [12]:
train

,Commercial & Office Buildings,Industrial & Manufacturing,Mixed Residential & Commercial Buildings,Multi-Family Elevator Buildings,Multi-Family Walk-Up Buildings,One & Two Family Buildings,Open Space and Outdoor Recreation,Parking Facilities,Public Facilities & Institutions,Transportation & Utility,...,22-23,23-24,Friday,Monday,Saturday,Sunday,Thursday,Tuesday,Wednesday,CrimeTypeID
48162,0,0,0,0,0,0,0,0,1,0,...,0,0,0,1,0,0,0,0,0,2
86027,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
83213,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,3
5608,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
165830,0,0,1,0,0,0,0,0,0,0,...,1,0,0,1,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117077,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,3
108204,0,0,0,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
137006,0,0,0,0,0,0,1,0,0,0,...,1,0,0,0,0,0,1,0,0,2
1866,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1
117394,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,3

In [13]:
validation

,Commercial & Office Buildings,Industrial & Manufacturing,Mixed Residential & Commercial Buildings,Multi-Family Elevator Buildings,Multi-Family Walk-Up Buildings,One & Two Family Buildings,Open Space and Outdoor Recreation,Parking Facilities,Public Facilities & Institutions,Transportation & Utility,...,22-23,23-24,Friday,Monday,Saturday,Sunday,Thursday,Tuesday,Wednesday,CrimeTypeID
38881,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,3
13699,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,2
20067,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,3
36866,1,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
12304,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22013,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,1,0,2
87933,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,1,0,0,1
6876,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,3
177762,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,2
173546,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1

In [14]:
test

,Commercial & Office Buildings,Industrial & Manufacturing,Mixed Residential & Commercial Buildings,Multi-Family Elevator Buildings,Multi-Family Walk-Up Buildings,One & Two Family Buildings,Open Space and Outdoor Recreation,Parking Facilities,Public Facilities & Institutions,Transportation & Utility,...,22-23,23-24,Friday,Monday,Saturday,Sunday,Thursday,Tuesday,Wednesday,CrimeTypeID
1036,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,1,0,1
146255,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
60766,0,0,1,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
4399,0,0,1,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
148181,1,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159690,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,1,0,3
131107,0,0,1,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,2
49716,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,1,0,0,0,1
78398,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,2
157112,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,3

In [12]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import log_loss
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import precision_score
feature_list = train.columns.tolist()
feature_list = feature_list[:len(feature_list) - 1]

In [33]:
#knn
from sklearn.neighbors import KNeighborsClassifier
model_knn = KNeighborsClassifier()
model_knn.fit(train[feature_list],train.CrimeTypeID)
pred_knn_value = np.array(model_knn.predict(test[feature_list]))
predicted_knn = np.array(model_knn.predict_proba(test[feature_list]))

In [35]:
log_loss(test.CrimeTypeID,predicted_knn),confusion_matrix(test.CrimeTypeID,pred_knn_value),f1_score(test.CrimeTypeID,pred_knn_value,average="weighted")

(5.341198304576128, array([[13147,  7287,  4837],
        [ 3360,  2590,  1729],
        [ 2790,  2102,  2473]], dtype=int64), 0.4750924405624924)

In [29]:
from sklearn.naive_bayes import BernoulliNB
model_NB = BernoulliNB()
model_NB.fit(train[feature_list], train.CrimeTypeID)
pred_NB_value = np.array(model_NB.predict(test[feature_list]))
predicted_NB = np.array(model_NB.predict_proba(test[feature_list]))
log_loss(test.CrimeTypeID,predicted_NB),confusion_matrix(test.CrimeTypeID,pred_NB_value),f1_score(test.CrimeTypeID,pred_NB_value,average="weighted")

(1.074395331831912, array([[14472,  6785,  4014],
        [ 2959,  3439,  1281],
        [ 2351,  2418,  2596]], dtype=int64), 0.5293506862390477)

In [31]:
from sklearn.linear_model import LogisticRegression
model_LR = LogisticRegression()
model_LR.fit(train[feature_list], train.CrimeTypeID)
pred_LR_value = np.array(model_LR.predict(test[feature_list]))
predicted_LR = np.array(model_LR.predict_proba(test[feature_list]))
log_loss(test.CrimeTypeID, predicted_LR),confusion_matrix(test.CrimeTypeID,pred_LR_value),f1_score(test.CrimeTypeID,pred_LR_value,average="weighted")

C:\Users\volca\.conda\envs\GEO503\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\volca\.conda\envs\GEO503\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)

(1.013077688644989, array([[14495,  6230,  4546],
        [ 2958,  3151,  1570],
        [ 2329,  2137,  2899]], dtype=int64), 0.5305427209251335)

In [32]:
from sklearn.ensemble import RandomForestClassifier  
model_RF = RandomForestClassifier()  
model_RF.fit(train[feature_list], train.CrimeTypeID)
pred_RF_value = np.array(model_RF.predict(test[feature_list]))
predicted_RF = np.array(model_RF.predict_proba(test[feature_list]))
log_loss(test.CrimeTypeID, predicted_RF),confusion_matrix(test.CrimeTypeID,pred_RF_value),f1_score(test.CrimeTypeID,pred_RF_value,average="weighted")

C:\Users\volca\.conda\envs\GEO503\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

(1.0162729518769775, array([[13773,  6290,  5208],
        [ 2783,  3138,  1758],
        [ 2121,  2100,  3144]], dtype=int64), 0.5208683630805486)

In [34]:
import lightgbm as lgb
model_lgb =lgb.LGBMClassifier(objective='multiclass', num_class=3,random_state=42).fit(train[feature_list], train.CrimeTypeID)
pred_lgb_value = np.array(model_lgb.predict(test[feature_list]))
predicted_lgb = np.array(model_lgb.predict_proba(test[feature_list]))
log_loss(test.CrimeTypeID, predicted_lgb),confusion_matrix(test.CrimeTypeID,pred_lgb_value),f1_score(test.CrimeTypeID,pred_lgb_value,average="weighted")

(1.0119382577393008, array([[14041,  6246,  4984],
        [ 2834,  3139,  1706],
        [ 2188,  2119,  3058]], dtype=int64), 0.5246782027506632)

In [15]:
from sklearn.feature_selection import VarianceThreshold

#方差选择法，返回值为特征选择后的数据
#参数threshold为方差的阈值
VarianceThreshold(threshold=0.1).fit_transform(train[feature_list])

array([[0, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       ...,
       [0, 0, 0],
       [0, 1, 0],
       [0, 1, 0]], dtype=uint8)